# Generated by Django 5.2.5 on 2025-08-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_slug_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
    ]
