# Generated by Django 5.2.5 on 2025-08-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_slug_alter_course_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['students_qty']},
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['students_qty'], name='shop_course_student_cd78ce_idx'),
        ),
    ]
